version: '1'

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules

services:
  next-app:
    container_name: fufuu-next-app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    restart: always
    ports:
      - 3000:3000