import './globals.css'
import type { Metadata } from 'next'
import { Inter, Sarabun } from 'next/font/google'
import '@mantine/core/styles.css';
import {theme} from '@/src/theme';

import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { MyHeader } from './components/header/MyHeader';
import { MyFooter } from './components/footer/MyFooter';

const inter = Inter({ subsets: ['latin'] })
export const sarabun = Sarabun({
  subsets: ['thai'],
  weight: "400"
})

export const metadata: Metadata = {
  title: 'fufuu Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <MyHeader/>
          {children}
          <MyFooter/>
        </MantineProvider>
      </body>
    </html>
  )
}
