import './globals.css'
import type { Metadata } from 'next'
import { Inter, Sarabun } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
export const sarabun = Sarabun({
  subsets: ['thai'],
  weight: "400"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sarabun.className}>{children}</body>
    </html>
  )
}
